name: fast_event_bus
description: 一个事件发送工具
version: 1.0.0
author: 康建群 kang_1994@outlook.com
homepage: https://github.com/StrangerKjq/flutter_event_bus

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
